### ISSUE TITLE
Demo Day Information - 

### ISSUE THREAD

**Issue by mdewey** [leafsicle/assignments#38]
With Demo Day approaching we are looking to collect your information.  This is information we will use to share with the community as well as our hiring partners. 

## Explorer Mode

- [x] Submit a pull request to this file with your updated information [https://github.com/suncoast-devs/demo-day/blob/master/src/profiles.json](https://github.com/suncoast-devs/demo-day/blob/master/src/profiles.json)
- [x] Submit here the link for the pull request that you create

**Comment by leafsicle** [comment]
https://github.com/suncoast-devs/demo-day/pull/4

**Comment by mdewey** [comment]
I am going to reject this for these reasons: 
- don't re-format the whole JSON file
- you modified files other than the JSON file


Re-submit/re-fork  this

**Comment by mdewey** [comment]
Your homework was marked: **Needs Improvement**

![Just a little further!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBHQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--77e95594d471321db6643ec08503d82a672249aa/giphy.gif)
> &ldquo;Just a little further!&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/14)**__

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBVdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5aaf4fb8aebc193771c4dd6c9823d8f6300ba70b/giphy-7.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/72)**__
